Import the dependencies ( modules )

In [10]:
import numpy as np
import pandas as pd
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn import svm


Set working directory

In [2]:
os.chdir('~/Downloads')

Load the data 

In [3]:
train = pd.read_csv('training.csv', encoding='cp1252')

test = pd.read_csv('test.csv')

Transform the result into integers and make the merge the data sets in order to encode it

In [4]:
def result_check(x):
    if x == 'H':
        return 1
    elif x == 'D':
        return 0
    else:
        return -1
train['result'] = train['FTR'].apply(result_check)
train = train[['Date','HomeTeam','AwayTeam','result']]
X = train.drop(['result'],axis=1)
X = X.append(test)
y = train['result']

convert categorical features to features that can be used with scikit-learn estimators

In [5]:
#Auto encodes any dataframe column of type category or object.
def dummyEncode(df):
        columnsToEncode = list(df.select_dtypes(include=['category','object']))
        le = LabelEncoder()
        for feature in columnsToEncode:
            try:
                df[feature] = le.fit_transform(df[feature])
            except:
                print('Error encoding '+feature)
        return df
X = dummyEncode(X)

Seperate the data set again in order to predict the outcome

In [6]:
X_test = X[len(train):]
X = X[:len(train)]


Apply cross validation

In [7]:
X_cv_train, X_cv_test, y_cv_train, y_cv_test = train_test_split(X, y, test_size=0.2, random_state=0)


Fit the model using the Random Forest algorithm

In [8]:
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_cv_train,y_cv_train)
clf.score(X_cv_test,y_cv_test)

0.39195979899497485

Make the prediction

In [9]:
clf.predict(X_test)

array([ 1,  1, -1, -1, -1, -1,  1,  1,  1,  1])

Use the support vector machine algorithm

In [11]:
clf_sv = svm.SVC()
clf_sv.fit(X_cv_train,y_cv_train)
clf_sv.score(X_cv_test,y_cv_test)

0.47236180904522612

Make the prediction

In [12]:
clf_sv.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Use the Naive bayesian classifier

In [14]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_cv_train,y_cv_train)
gnb.score(X_cv_test,y_cv_test)

0.4899497487437186

In [15]:
gnb.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])